function BadWords() {
    const badWords = ["Fuck",
        "bisung",
        "pussy",
        "bayot",
        "gay",
        "moron",
        "Bilat",
        "Vagina",
        "Bisong",
        "Pussy",
        "Bogo",
        "Stupid",
        "Borikat",
        "Whore",
        "Boyset",
        "Bullshit",
        "chupa",
        "Iyot",
        "sex",
        "iyota",
        "iyoton",
        "Kayata",
        "Kayaton",
        "KULERA",
        "CHOLERA",
        "Litse",
        "Shit",
        "oten",
        "dick",
        "otin",
        "Pisti",
        "Piste",
        "yawa'a",
        "yawa a",
        "fuckhead",
        "putangina",
        "putang ina",
        "fucker",
        "Totoy",
        "Boobs",
        "Uwagan",
        "Slut",
        "yawa",
        "yawa!",
        "yawa",
        "bweset",
        "bweset!",
        "devil"];

    return badWords;
}

module.exports = { BadWords };